### ISSUE TITLE
Travis-Ci Error

### ISSUE THREAD

**Issue by justinsoon** [ShikherVerma/resume#4]
Getting an error trying to build it.

From Travis-Ci Console vvv
```
$ cd justinsoon/resume
$ git checkout -qf b33eafc8643d81a19d32b3cb35403f90f857579e
fatal: reference is not a tree: b33eafc8643d81a19d32b3cb35403f90f857579e
The command "git checkout -qf b33eafc8643d81a19d32b3cb35403f90f857579e" failed and exited with 128 during .
```

**Comment by ShikherVerma** [comment]
@justinsoon I created a throw away account ( @thr0w0 ). [forked](https://github.com/thr0w0/resume) and followed all the steps in the readme; it [build fine](https://travis-ci.org/thr0w0/resume/builds/263653590) for me!

Most probably your error has occurred because you forced push before the travis build job had a chance to clone and checkout the `b33eafc8643d81a19d32b3cb35403f90f857579e` commit!
You can fix it by running:
```bash
git commit --amend --no-edit
git push origin master -f
```

**Comment by justinsoon** [comment]
Thanks it worked!
